-- ============================================================================
-- Math 110.1 — Exercise 12
-- Prime and Maximal Ideals, Fields of Quotients
-- Run AFTER schema.sql and seed-math110-3rd-exam.sql. Safe to re-run.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Course (update name if 3rd-exam already ran)
-- ---------------------------------------------------------------------------
insert into public.courses (id, code, name, description) values
  ('cd574181-02fb-4093-9e23-f268fea6baff', 'MATH 110.1', 'Abstract Algebra I',
   'Groups, rings, fields, ideals, homomorphisms, and fields of quotients.')
on conflict (code) do update set name = excluded.name, description = excluded.description;

-- ---------------------------------------------------------------------------
-- Topics
-- ---------------------------------------------------------------------------
insert into public.topics (id, course_id, name, description) values
  ('656800c1-6424-48fd-b98d-0e1869bc0993', 'cd574181-02fb-4093-9e23-f268fea6baff',
   'Prime and Maximal Ideals', 'Characterizing ideals via quotient rings in Z_n and Z x Z.'),
  ('7977cbab-91ae-4b90-ac11-632565468414', 'cd574181-02fb-4093-9e23-f268fea6baff',
   'Fields of Quotients', 'Constructing the field of fractions from an integral domain.')
on conflict (course_id, name) do nothing;

-- ---------------------------------------------------------------------------
-- Questions (14 parts of Exercise 12)
-- ---------------------------------------------------------------------------

insert into public.questions
  (id, course_id, topic_id, title, question_text, difficulty, year, exam_name, question_number, hint, answer, solution)
values

-- ===== Q1: <6> prime/maximal in Z_12 =====
(
  'b93a06e0-5aa0-4462-8393-cc2f95ca2309',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '656800c1-6424-48fd-b98d-0e1869bc0993',
  'Is $\langle 6 \rangle$ a Maximal or Prime Ideal of $\mathbb{Z}_{12}$?',
  $q$Consider the ring $\mathbb{Z}_{12}$ under addition and multiplication modulo $12$. Is $\langle 6 \rangle$ a maximal ideal of $\mathbb{Z}_{12}$? Is it a prime ideal of $\mathbb{Z}_{12}$?$q$,
  'medium',
  2023,
  'Exercise 12',
  1,
  $q$An ideal $P$ is prime iff $R/P$ is an integral domain; it is maximal iff $R/P$ is a field. Compute $\mathbb{Z}_{12}/\langle 6 \rangle$ and look for zero divisors.$q$,
  $q$**Neither.** $\langle 6 \rangle$ is not a prime ideal and not a maximal ideal of $\mathbb{Z}_{12}$.$q$,
  $q$\langle 6 \rangle = \{0, 6\} \subseteq \mathbb{Z}_{12}$ is the principal ideal generated by $6$. The quotient $\mathbb{Z}_{12}/\langle 6 \rangle$ is a commutative ring with unity $1 + \langle 6 \rangle$.

In $\mathbb{Z}_{12}/\langle 6 \rangle$,

$$(2 + \langle 6 \rangle)(3 + \langle 6 \rangle) = 6 + \langle 6 \rangle = \langle 6 \rangle,$$

where $2 + \langle 6 \rangle \neq \langle 6 \rangle$ and $3 + \langle 6 \rangle \neq \langle 6 \rangle$. Hence $2 + \langle 6 \rangle$ is a zero divisor of $\mathbb{Z}_{12}/\langle 6 \rangle$, so $\mathbb{Z}_{12}/\langle 6 \rangle$ is not an integral domain and therefore not a field.

$\therefore$ $\langle 6 \rangle$ is not a prime ideal of $\mathbb{Z}_{12}$.

$\therefore$ $\langle 6 \rangle$ is not a maximal ideal of $\mathbb{Z}_{12}$. $\blacksquare$$q$
),

-- ===== Q2: <3> prime/maximal in Z_12 =====
(
  '7d449fa5-babc-436b-8efd-96a5ea3747c3',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '656800c1-6424-48fd-b98d-0e1869bc0993',
  'Is $\langle 3 \rangle$ a Maximal or Prime Ideal of $\mathbb{Z}_{12}$?',
  $q$Consider the ring $\mathbb{Z}_{12}$. Is $\langle 3 \rangle$ a maximal ideal of $\mathbb{Z}_{12}$? Is it a prime ideal of $\mathbb{Z}_{12}$? $q$,
  'medium',
  2023,
  'Exercise 12',
  2,
  $q$Compute $\mathbb{Z}_{12}/\langle 3 \rangle$. How many elements does it have? Show every nonzero element is a unit.$q$,
  $q$**Both.** $\langle 3 \rangle$ is a maximal ideal and a prime ideal of $\mathbb{Z}_{12}$.$q$,
  $q$\langle 3 \rangle = \{0, 3, 6, 9\} \subseteq \mathbb{Z}_{12}$ is the principal ideal generated by $3$. The quotient $\mathbb{Z}_{12}/\langle 3 \rangle$ is a commutative ring with unity $1 + \langle 3 \rangle$.

Since every nonzero element has an inverse:

$$(1 + \langle 3 \rangle)^{-1} = 1 + \langle 3 \rangle, \qquad (2 + \langle 3 \rangle)^{-1} = 2 + \langle 3 \rangle,$$

because $2 \cdot 2 = 4 \equiv 1 \pmod{3}$. Therefore $\mathbb{Z}_{12}/\langle 3 \rangle$ is a field, and is therefore an integral domain.

$\therefore$ $\langle 3 \rangle$ is a maximal ideal of $\mathbb{Z}_{12}$.

$\therefore$ $\langle 3 \rangle$ is a prime ideal of $\mathbb{Z}_{12}$. $\blacksquare$$q$
),

-- ===== Q3: <6> prime/maximal in <3> =====
(
  'fb999b3e-a466-4bc9-bbf0-e986bd44482c',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '656800c1-6424-48fd-b98d-0e1869bc0993',
  'Is $\langle 6 \rangle$ a Maximal or Prime Ideal of $\langle 3 \rangle$?',
  $q$Consider the ring $\mathbb{Z}_{12}$ with $\langle 3 \rangle = \{0, 3, 6, 9\}$. Is $\langle 6 \rangle$ a maximal ideal of the ring $\langle 3 \rangle$? Is it a prime ideal of $\langle 3 \rangle$? $q$,
  'medium',
  2023,
  'Exercise 12',
  3,
  $q$First show $\langle 6 \rangle$ is an ideal of $\langle 3 \rangle$ using the ideal subring test, then compute the quotient and check if it is a field.$q$,
  $q$**Both.** $\langle 6 \rangle$ is a maximal ideal and a prime ideal of $\langle 3 \rangle$.$q$,
  $q$**Ideal subring test.** Clearly $\langle 6 \rangle = \{0, 6\} \neq \{0\}$ and $\langle 6 \rangle \subseteq \{0, 3, 6, 9\} = \langle 3 \rangle$. Since $\langle 6 \rangle$ is an ideal of $\mathbb{Z}_{12} \supseteq \langle 3 \rangle$, it is closed under subtraction and under multiplication by every element of $\mathbb{Z}_{12}$, hence by every element of $\langle 3 \rangle$. So $\langle 6 \rangle$ is an ideal of $\langle 3 \rangle$.

The quotient ring

$$\langle 3 \rangle / \langle 6 \rangle = \{\langle 6 \rangle,\ 3 + \langle 6 \rangle\}$$

is a commutative ring with unity $3 + \langle 6 \rangle$ (note $9 + \langle 6 \rangle = 3 + \langle 6 \rangle$ since $9 - 3 = 6 \in \langle 6 \rangle$). Since $\langle 3 \rangle / \langle 6 \rangle$ has exactly two elements, it is isomorphic to $\mathbb{Z}_2$, which is a field.

$\therefore$ $\langle 6 \rangle$ is a maximal ideal of $\langle 3 \rangle$.

$\therefore$ $\langle 6 \rangle$ is a prime ideal of $\langle 3 \rangle$. $\blacksquare$$q$
),

-- ===== Q4: S = {(a,0)} is ideal of Z x Z =====
(
  '3d7084c1-6e36-41b6-bed9-4483375d0d81',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '656800c1-6424-48fd-b98d-0e1869bc0993',
  '$S = \{(a, 0) \mid a \in \mathbb{Z}\}$ is an Ideal of $\mathbb{Z} \times \mathbb{Z}$',
  $q$Consider the ring $R = \mathbb{Z} \times \mathbb{Z}$ under coordinate-wise addition and multiplication. Let $S = \{(a, 0) \mid a \in \mathbb{Z}\}$. Show that $S$ is an ideal of $R$.$q$,
  'medium',
  2023,
  'Exercise 12',
  4,
  $q$Use the ideal subring test: (i) closed under subtraction, (ii) absorbs multiplication by all of $R$ from both sides.$q$,
  $q$**$S$ is an ideal of $\mathbb{Z} \times \mathbb{Z}$.** Verified via the ideal test.$q$,
  $q$**Ideal subring test.** Clearly by definition $S \neq \emptyset$ and $S \subseteq R$.

**(i)** Let $(a, 0), (b, 0) \in S$ for some $a, b \in \mathbb{Z}$. Then

$$(a, 0) - (b, 0) = (a - b, 0) \in S,$$

since $a - b \in \mathbb{Z}$. So $S$ is an additive subgroup of $R$.

**(ii)** Let $(r, s) \in R$ and $(a, 0) \in S$ for some $a, r, s \in \mathbb{Z}$. Then

$$(r, s)(a, 0) = (ra, 0) \in S, \qquad (a, 0)(r, s) = (ar, 0) \in S,$$

since $ra, ar \in \mathbb{Z}$.

$\therefore$ $S$ is an ideal of $R$. $\blacksquare$$q$
),

-- ===== Q5: S is prime in Z x Z =====
(
  '2b8982b3-ded8-42e6-b50b-7627e64f2c56',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '656800c1-6424-48fd-b98d-0e1869bc0993',
  '$S = \{(a, 0)\}$ is a Prime Ideal of $\mathbb{Z} \times \mathbb{Z}$',
  $q$Consider $R = \mathbb{Z} \times \mathbb{Z}$ and $S = \{(a, 0) \mid a \in \mathbb{Z}\}$, which is an ideal of $R$. Prove that $S$ is a prime ideal of $R$.$q$,
  'hard',
  2023,
  'Exercise 12',
  5,
  $q$Show $R/S$ is an integral domain. Identify the cosets and show there are no zero divisors in the quotient.$q$,
  $q$**$S$ is a prime ideal of $\mathbb{Z} \times \mathbb{Z}$.**$q$,
  $q$By the previous result, $S$ is a proper ideal of $R$. Consider the factor ring $R/S$, which is commutative with unity $(0,1) + S$:

$$R/S = \{\ldots,\; (0,-2)+S,\; (0,-1)+S,\; S,\; (0,1)+S,\; (0,2)+S,\; \ldots\}.$$

Let $(0,a) + S$ be a nonzero element of $R/S$ (so $a \neq 0$). Suppose

$$[(0,a) + S]\,[(0,b) + S] = S$$

for some $(0,b) + S \in R/S$. Since

$$[(0,a) + S]\,[(0,b) + S] = (0, ab) + S,$$

we get $(0, ab) \in S$, i.e. $ab = 0$. As $\mathbb{Z}$ is an integral domain and $a \neq 0$, it follows that $b = 0$, so $(0,b) + S = S$.

Hence $R/S$ has no zero divisors. Therefore $R/S$ is an integral domain.

$\therefore$ $S$ is a prime ideal of $R$. $\blacksquare$$q$
),

-- ===== Q6: S is NOT maximal in Z x Z =====
(
  '61e25c38-7d7c-4370-aa70-5cfd097e2469',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '656800c1-6424-48fd-b98d-0e1869bc0993',
  '$S = \{(a, 0)\}$ is NOT a Maximal Ideal of $\mathbb{Z} \times \mathbb{Z}$',
  $q$Consider $R = \mathbb{Z} \times \mathbb{Z}$ and $S = \{(a, 0) \mid a \in \mathbb{Z}\}$. Is $S$ a maximal ideal of $R$? Justify your answer.$q$,
  'medium',
  2023,
  'Exercise 12',
  6,
  $q$An ideal is maximal iff the quotient is a field. Show some nonzero element of $R/S$ has no inverse.$q$,
  $q$**No.** $S$ is not a maximal ideal of $\mathbb{Z} \times \mathbb{Z}$.$q$,
  $q$Consider the factor ring $R/S$. Take $(0,2) + S \in R/S$, which is nonzero. We show it has no multiplicative inverse: there is no $(0,c) + S \in R/S$ with

$$[(0,2) + S]\,[(0,c) + S] = (0, 2c) + S = (0, 1) + S,$$

because that would require $2c = 1$ for some integer $c$, which is impossible in $\mathbb{Z}$.

Hence $R/S$ is not a field. Therefore $S$ is not a maximal ideal of $R$. $\blacksquare$$q$
),

-- ===== Q7: ker phi is prime =====
(
  '17b9ae9e-445d-4653-83d5-77b8f908924b',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '656800c1-6424-48fd-b98d-0e1869bc0993',
  'Kernel of an Epimorphism is Prime',
  $q$Let $R$ and $R'$ be rings and $\varphi: R \to R'$ a ring epimorphism. Prove that if $R$ is a commutative ring with unity and $R'$ is an integral domain, then $\ker \varphi$ is a prime ideal of $R$.$q$,
  'hard',
  2023,
  'Exercise 12',
  7,
  $q$Apply the First Isomorphism Theorem: $R/\ker\varphi \cong \varphi(R) = R'$. An ideal $P$ is prime iff $R/P$ is an integral domain.$q$,
  $q$**$\ker \varphi$ is a prime ideal of $R$.**$q$,
  $q$Suppose $R$ is a commutative ring with unity and $R'$ is an integral domain.

By a standard theorem, $\ker \varphi$ is an ideal of $R$. Consider the factor ring $R/\ker \varphi$. By the First Isomorphism Theorem for rings,

$$R / \ker \varphi \cong \varphi(R).$$

Since $\varphi$ is a ring epimorphism, it is surjective, so $\varphi(R) = R'$. Hence

$$R / \ker \varphi \cong R'.$$

Since $R'$ is an integral domain and the property of being an integral domain is preserved under ring isomorphism, $R/\ker \varphi$ is also an integral domain.

A proper ideal $P$ of a commutative ring is prime exactly when $R/P$ is an integral domain. (Since $R'$ is an integral domain, $R' \neq \{0\}$, and surjectivity forces $\ker \varphi \neq R$.)

$\therefore$ $\ker \varphi$ is a prime ideal of $R$. $\blacksquare$$q$
),

-- ===== Q8: p = ab implies a or b unit =====
(
  '3fd69615-ead3-4f4a-b4c3-57512a7e6b7f',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '656800c1-6424-48fd-b98d-0e1869bc0993',
  'Prime Element in an Integral Domain',
  $q$Let $D$ be an integral domain and $0 \neq p \in D$. Suppose the principal ideal $\langle p \rangle$ is a prime ideal of $D$. Prove that if $p = ab$, then either $a$ is a unit of $D$ or $b$ is a unit of $D$.$q$,
  'hard',
  2023,
  'Exercise 12',
  8,
  $q$From $ab = p \in \langle p \rangle$ and primeness, one factor lies in $\langle p \rangle$; write it as $pk$ and cancel $p$ using the cancellation law (valid in an integral domain).$q$,
  $q$Either $a$ is a unit or $b$ is a unit of $D$.$q$,
  $q$Suppose $p = ab$. Then $0 \neq a, b \in D$.

Since $\langle p \rangle$ is a prime ideal,

$$p = ab \in \langle p \rangle \implies a \in \langle p \rangle \;\text{or}\; b \in \langle p \rangle.$$

**Case 1:** $a \in \langle p \rangle$. Then $a = pk$ for some $0 \neq k \in D$, and

$$p = ab \implies p = pkb \implies 1 = kb$$

by the cancellation law ($D$ is an integral domain and $p \neq 0$). Hence $b$ is a unit.

**Case 2:** $b \in \langle p \rangle$. Then $b = \ell p$ for some $\ell \in D$, and

$$p = ab \implies p = a\ell p \implies 1 = a\ell$$

by the cancellation law. Hence $a$ is a unit.

$\therefore$ Either $a$ is a unit or $b$ is a unit of $D$. $\blacksquare$$q$
),

-- ===== Q9: [ka,kb] = [a,b] =====
(
  '8fe2cde7-4dc1-4925-88cd-c77d1d1e34d3',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '7977cbab-91ae-4b90-ac11-632565468414',
  'Equivalence in the Field of Quotients',
  $q$Given an integral domain $D$ and its field of quotients $F = \{[a, b] \mid a, b \in D,\; b \neq 0\}$. Show that if $0 \neq k \in D$ and $[a,b] \in F$, then $[ka, kb] = [a, b]$.$q$,
  'easy',
  2023,
  'Exercise 12',
  9,
  $q$Recall the definition: $[x, y] = [u, v]$ in $F$ iff $xv = yu$. Compute $(ka)b$ and $(kb)a$.$q$,
  $q$**$[ka, kb] = [a, b]$.**$q$,
  $q$Suppose $0 \neq k \in D$ and $[a, b] \in F$, so $a, b \in D$ with $b \neq 0$. Then

$$(ka) b = k a b = (kb) a,$$

which is precisely the condition for $[ka, kb] = [a, b]$ in $F$. $\blacksquare$$q$
),

-- ===== Q10: left distributivity =====
(
  '920336fe-7ab1-48dc-b926-04d1ca128533',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '7977cbab-91ae-4b90-ac11-632565468414',
  'Left Distributivity in F',
  $q$Given an integral domain $D$ with field of quotients $F = \{[a, b] \mid a, b \in D,\; b \neq 0\}$, verify that $F$ satisfies the left distributivity law.$q$,
  'medium',
  2023,
  'Exercise 12',
  10,
  $q$Expand both sides using $[c,d]+[e,f] = [cf+de,\ df]$ and $[x,y][u,v] = [xu,yv]$, then multiply numerator and denominator by $b$ to reach a common form.$q$,
  $q$**$[a,b]\big([c,d]+[e,f]\big) = [a,b][c,d] + [a,b][e,f]$.**$q$,
  $q$Let $[a,b], [c,d], [e,f] \in F$ with $b, d, f \neq 0$.

$$\begin{aligned}
[a,b]\big([c,d]+[e,f]\big) &= [a,b][cf+de,\ df] \\
  &= [a(cf+de),\ bdf] \\
  &= [acf + ade,\ bdf] \\
  &= [b(acf + ade),\ b(bdf)] \\
  &= [acbf + aebd,\ b^2df] \\
  &= [(ac)(bf) + (ab)(de),\ (bd)(bf)] \\
  &= [ac, bd] + [ae, bf] \\
  &= [a,b][c,d] + [a,b][e,f].
\end{aligned}$$

The step from line 2 to line 3 uses the result $[kx,ky] = [x,y]$ (with $k=b$) to multiply numerator and denominator by $b$. The step from line 5 to line 6 uses the addition rule for a common denominator.

$\therefore$ $F$ satisfies the left distributive law. $\blacksquare$$q$
),

-- ===== Q11: zero element and unity =====
(
  '7a1279c5-9bb3-4005-8b74-b0dd61ec13c7',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '7977cbab-91ae-4b90-ac11-632565468414',
  'Zero Element and Unity in F',
  $q$Given an integral domain $D$ with field of quotients $F = \{[a, b] \mid a, b \in D,\; b \neq 0\}$. Identify the zero element (additive identity) and the unity (multiplicative identity) in $F$.$q$,
  'easy',
  2023,
  'Exercise 12',
  11,
  $q$Try $[0,1]$ for the additive identity and $[1,1]$ for the multiplicative identity. Verify each using the definitions of addition and multiplication in $F$.$q$,
  $q$**Zero element: $[0,1]$. Unity: $[1,1]$.**$q$,
  $q$Let $[a, b] \in F$ with $b \neq 0$.

**Zero element:** Consider $[0, 1] \in F$. Then

$$[a, b] + [0, 1] = [a \cdot 1 + 0 \cdot b,\; b \cdot 1] = [a, b].$$

$\therefore$ $[0,1]$ is the additive identity.

**Unity:** Consider $[1, 1] \in F$. Then

$$[a, b][1, 1] = [a \cdot 1,\; b \cdot 1] = [a, b].$$

$\therefore$ $[1,1]$ is the multiplicative identity. $\blacksquare$$q$
),

-- ===== Q12: additive inverse =====
(
  '19a9c792-b223-4011-9469-17447752428a',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '7977cbab-91ae-4b90-ac11-632565468414',
  'Additive Inverse in F',
  $q$Given an integral domain $D$ with field of quotients $F = \{[a, b] \mid a, b \in D,\; b \neq 0\}$. Give the additive inverse of an element $[a, b] \in F$.$q$,
  'easy',
  2023,
  'Exercise 12',
  12,
  $q$Try $[-a, b]$ and compute $[a,b]+[-a,b]$. Use $[kx,ky] = [x,y]$ to simplify the result.$q$,
  $q$**The additive inverse of $[a,b]$ is $[-a, b]$.**$q$,
  $q$Let $[a, b] \in F$ with $b \neq 0$. Since $D$ is a ring, $-a \in D$, so $[-a, b] \in F$. Then

$$[a, b] + [-a, b] = [a \cdot b + (-a) \cdot b,\; b \cdot b] = [ab - ab,\; b^2] = [0, b^2].$$

By the result $[kx, ky] = [x, y]$ with $k = b$, $x = 0$, $y = b$, we get $[0, b^2] = [0, 1]$.

$\therefore$ $[-a, b]$ is the additive inverse of $[a, b]$. $\blacksquare$$q$
),

-- ===== Q13: multiplicative inverse =====
(
  '690f37c2-f44b-4c0f-a1d2-083ad0f25879',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '7977cbab-91ae-4b90-ac11-632565468414',
  'Multiplicative Inverse in F',
  $q$Given an integral domain $D$ with field of quotients $F = \{[a, b] \mid a, b \in D,\; b \neq 0\}$. Identify the multiplicative inverse of a nonzero element $[a, b] \in F$.$q$,
  'easy',
  2023,
  'Exercise 12',
  13,
  $q$Try $[b, a]$ (note: nonzero means $a \neq 0$, so $[b,a] \in F$). Compute $[a,b][b,a]$ and use $[kx,ky] = [x,y]$.$q$,
  $q$**The multiplicative inverse of $[a,b]$ is $[b, a]$.**$q$,
  $q$Let $[a, b] \in F$ be nonzero, so $a, b \in D$ with $a, b \neq 0$. Then $[b, a] \in F$, and

$$[a, b][b, a] = [a \cdot b,\; b \cdot a] = [ab, ab].$$

By the result $[kx, ky] = [x, y]$ with $k = ab$, $x = 1$, $y = 1$, we get $[ab, ab] = [1, 1]$, which is the unity of $F$.

$\therefore$ $[b, a]$ is the multiplicative inverse of $[a, b]$. $\blacksquare$$q$
),

-- ===== Q14: subring isomorphic to D =====
(
  '26ef19a5-e9ab-4149-b015-a58b0bc76052',
  'cd574181-02fb-4093-9e23-f268fea6baff',
  '7977cbab-91ae-4b90-ac11-632565468414',
  'Subring of $F$ Isomorphic to $D$',
  $q$Given an integral domain $D$ with field of quotients $F = \{[a, b] \mid a, b \in D,\; b \neq 0\}$. Give explicitly the subring of $F$ which is isomorphic to $D$.$q$,
  'medium',
  2023,
  'Exercise 12',
  14,
  $q$Consider the map $\varphi: D \to F$ given by $\varphi(a) = [a, 1]$. Compute $\ker \varphi$ and apply the First Isomorphism Theorem.$q$,
  $q$**The subring $\{[a, 1] \mid a \in D\}$ is isomorphic to $D$ via $a \mapsto [a, 1]$.**$q$,
  $q$Consider the mapping $\varphi: D \to F$ given by $\varphi(a) = [a, 1]$.

For $a, b \in D$:

$$\varphi(a) + \varphi(b) = [a, 1] + [b, 1] = [a + b, 1] = \varphi(a + b),$$

$$\varphi(a)\,\varphi(b) = [a, 1][b, 1] = [ab, 1] = \varphi(ab).$$

So $\varphi$ is a ring homomorphism.

**Kernel:**

$$\ker \varphi = \{a \in D \mid \varphi(a) = [0, 1]\} = \{a \in D \mid [a, 1] = [0, 1]\}.$$

Now $[a, 1] = [0, 1] \iff a \cdot 1 = 1 \cdot 0 \iff a = 0$, so $\ker \varphi = \{0\}$.

By the First Isomorphism Theorem for rings,

$$\varphi(D) \cong D / \ker \varphi = D / \{0\} \cong D.$$

$\therefore$ $D$ is isomorphic to $\varphi(D) = \{[a, 1] \mid a \in D\}$, which is a subring of $F$. $\blacksquare$$q$
)
on conflict (id) do nothing;
