-- ============================================================================
-- Math 110.1 Exercise 5 — cyclic groups, orders of elements
-- 5 problems with solutions, converted from Typst to Markdown + LaTeX.
-- ============================================================================

insert into public.questions
  (id, course_id, topic_id, title, question_text, difficulty, year, exam_name, question_number, hint, answer, solution)
values
  (
    '7612d9f0-bb8f-4394-97e0-86c87ae6dec4',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Cyclic Subgroups of $\\mathbb{Z}_{12}$ and $D_4$',
    $BODY$Consider the following groups. For each group below, do the following:

- List all the cyclic subgroups of each group.
- Determine the orders of every element of the group.
- Which of the groups is cyclic? For the cyclic group, identify all the generators.

**(a)** $\mathbb{Z}_{12} = \{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11\}$

**(b)** $D_4 = \{R_{0^{\circ}}, R_{90^{\circ}}, R_{180^{\circ}}, R_{270^{\circ}}, v, h, d_1, d_2\}$ $BODY$,
    'hard',
    2026,
    'Exercise 5',
    1,
    $BODY$For $\mathbb{Z}_{12}$, list the subgroup generated by each element — they repeat. For $D_4$, the rotations $R_{0^{\circ}}, R_{90^{\circ}}, R_{180^{\circ}}, R_{270^{\circ}}$ form a cyclic subgroup, and each reflection generates a subgroup of order $2$.$BODY$,
    $BODY$**(a)** $\mathbb{Z}_{12}$ is cyclic with generators $1, 5, 7, 11$.

**(b)** $D_4$ is not cyclic — no single element generates all of $D_4$.$BODY$,
    $BODY$**(a)** $\mathbb{Z}_{12} = \{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11\}$

**Cyclic subgroups:**

- $\langle 0 \rangle = \{0\}$
- $\langle 1 \rangle = \langle 5 \rangle = \langle 7 \rangle = \langle 11 \rangle = \mathbb{Z}_{12}$
- $\langle 2 \rangle = \langle 10 \rangle = \{0, 2, 4, 6, 8, 10\}$
- $\langle 3 \rangle = \langle 9 \rangle = \{0, 3, 6, 9\}$
- $\langle 4 \rangle = \langle 8 \rangle = \{0, 4, 8\}$
- $\langle 6 \rangle = \{0, 6\}$

**Orders of elements:**

$$|0| = 1, \quad |1| = |5| = |7| = |11| = 12, \quad |2| = |10| = 6, \quad |3| = |9| = 4, \quad |4| = |8| = 3, \quad |6| = 2.$$

$\therefore$ $\mathbb{Z}_{12}$ is cyclic with $1, 5, 7$, and $11$ as generators. $\blacksquare$

---

**(b)** $D_4 = \{R_{0^{\circ}}, R_{90^{\circ}}, R_{180^{\circ}}, R_{270^{\circ}}, v, h, d_1, d_2\}$

**Cyclic subgroups:**

- $\langle R_{0^{\circ}} \rangle = \{R_{0^{\circ}}\}$
- $\langle R_{90^{\circ}} \rangle = \langle R_{270^{\circ}} \rangle = \{R_{0^{\circ}}, R_{90^{\circ}}, R_{180^{\circ}}, R_{270^{\circ}}\}$
- $\langle R_{180^{\circ}} \rangle = \{R_{0^{\circ}}, R_{180^{\circ}}\}$
- $\langle v \rangle = \{R_{0^{\circ}}, v\}$
- $\langle h \rangle = \{R_{0^{\circ}}, h\}$
- $\langle d_1 \rangle = \{R_{0^{\circ}}, d_1\}$
- $\langle d_2 \rangle = \{R_{0^{\circ}}, d_2\}$

**Orders of elements:**

$$|R_{0^{\circ}}| = 1, \quad |R_{90^{\circ}}| = |R_{270^{\circ}}| = 4, \quad |R_{180^{\circ}}| = |v| = |h| = |d_1| = |d_2| = 2.$$

$\therefore$ $D_4$ is **not** a cyclic group since it has no generator. $\blacksquare$$BODY$
  ),
  (
    '3f071825-1d47-48a1-b820-ebc6f0c3db8f',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    '$a^m = e$ if and only if $n \\mid m$',
    $BODY$Prove: Let $G$ be a group with identity $e$. If $a \in G$ is of order $n$, then $a^m = e$ if and only if $n \mid m$.$BODY$,
    'hard',
    2026,
    'Exercise 5',
    2,
    $BODY$For $(\Rightarrow)$, use the Division Algorithm to write $m = nq + r$ with $0 \le r < n$, then show $a^r = e$ forces $r = 0$ by minimality of $n$.$BODY$,
    $BODY$$a^m = e \iff n \mid m$.$BODY$,
    $BODY$Suppose $a \in G$ is of order $n$.

$(\Rightarrow)$ Suppose $a^m = e$. Since $|a| = n > 0$, we have $a^n = e$. By the Division Algorithm in $\mathbb{Z}$, $m = nq + r$ for some $q, r \in \mathbb{Z}$ with $0 \le r < n$. It follows that

$$
\begin{equation*}a^m = a^{nq + r} = (a^n)^q a^r = e^q a^r = a^r = e.\end{equation*}
$$

Since $n$ is the least positive integer $\ell$ such that $a^{\ell} = e$ and $0 \le r < n$, then $r = 0$. Hence,

$$
\begin{equation*}m = nq \implies n \mid m.\end{equation*}
$$

$(\Leftarrow)$ Suppose $n \mid m$. Then, $m = nk$ for some $k \in \mathbb{Z}$. Since $|a| = n$, we have $a^n = e$. It follows that

$$
\begin{equation*}a^m = a^{nk} = (a^n)^k = e^k = e.\end{equation*}
$$

$\therefore$ $a^m = e \iff n \mid m$. $\blacksquare$$BODY$
  ),
  (
    'e000dec1-ef1f-4b19-b242-b8c2080cf3aa',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    '$a^m = a^r$ Where $r$ is the Remainder Mod $n$',
    $BODY$Let $G$ be a group and $a \in G$ be an element of order $n$. Show that $a^m = a^r$, where $r$ is the remainder when $m$ is divided by $n$.$BODY$,
    'easy',
    2026,
    'Exercise 5',
    3,
    $BODY$Write $m = nq + r$ via the Division Algorithm and use $a^n = e$ to simplify $a^{nq + r}$.$BODY$,
    $BODY$By the Division Algorithm, $m = nq + r$, so $a^m = (a^n)^q a^r = e^q a^r = a^r$.$BODY$,
    $BODY$Since $|a| = n$, then $a^n = e$. Let $m \in \mathbb{Z}$. By the Division Algorithm in $\mathbb{Z}$, $m = nq + r$ for some $q, r \in \mathbb{Z}$ with $0 \le r < n$. Then,

$$
\begin{equation*}a^m = a^{nq + r} = (a^n)^q a^r = e^q a^r = a^r.\end{equation*}
$$

$\therefore$ $a^m = a^r$, as desired. $\blacksquare$$BODY$
  ),
  (
    '81a3d57a-10e6-4024-9ff5-d1894bf57856',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    '$a$ and $bab^{-1}$ Have the Same Order',
    $BODY$Let $G$ be a group and $a, b \in G$. Show that $a$ and $bab^{-1}$ have the same order.$BODY$,
    'hard',
    2026,
    'Exercise 5',
    4,
    $BODY$Show by induction that $(bab^{-1})^k = ba^k b^{-1}$ for all $k \ge 1$, then argue $(bab^{-1})^k = e \iff a^k = e$.$BODY$,
    $BODY$$|bab^{-1}| = |a|$, since $(bab^{-1})^k = ba^k b^{-1}$ and $ba^k b^{-1} = e \iff a^k = e$.$BODY$,
    $BODY$Let $|a| = n$. It follows that $a^n = e$. Note that

$$
\begin{aligned}
(bab^{-1})^k &= \underbrace{(bab^{-1})(bab^{-1}) \cdots (bab^{-1})}_{k \text{ times}} \\
             &= ba^k b^{-1}.
\end{aligned}
$$

Hence,

$$
\begin{equation*}(bab^{-1})^k = ba^k b^{-1} = e \iff a^k = e.\end{equation*}
$$

Since $n$ is the least $k$ such that $a^k = e$, it follows that the least $k$ with $(bab^{-1})^k = e$ is also $n$, and hence $|bab^{-1}| = n$.

$\therefore$ $|a| = |bab^{-1}|$, as desired. $\blacksquare$$BODY$
  ),
  (
    '1eba89ab-f318-43a6-9b39-c1f877c00ffb',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Elements of Finite Order Form a Subgroup',
    $BODY$Show that the elements of finite order in an abelian group $G$ form a subgroup of $G$.$BODY$,
    'hard',
    2026,
    'Exercise 5',
    5,
    $BODY$Let $H = \{g \in G \mid g \text{ is of finite order}\}$. Use the three-step subgroup test. For closure, if $|a| = m$ and $|b| = n$, show $(ab)^{mn} = e$ using abelianness.$BODY$,
    $BODY$The set $H = \{g \in G \mid g \text{ has finite order}\}$ is a subgroup of $G$.$BODY$,
    $BODY$Let $G$ be an abelian group. Let $H = \{g \in G \mid g \text{ is of finite order}\}$. Let $e$ be the identity in $G$.

$\subseteq$: Clearly, $H \subseteq G$ by definition.

**(i)** Let $a, b \in H$. Then, $a$ and $b$ are of finite order, say $|a| = m$ and $|b| = n$. Then, $a^m = e$ and $b^n = e$. Since $G$ is abelian, it follows that

$$
\begin{equation*}(ab)^{mn} = a^{mn} b^{mn} = (a^m)^n (b^n)^m = e^n e^m = e.\end{equation*}
$$

Hence, $|ab| \mid mn$, and since $mn \in \mathbb{Z}^{+}$, then $|ab| \in \mathbb{Z}^{+}$, so $ab$ is of finite order. Hence, $ab \in H$.

**(ii)** Consider $e \in G$. Since $|e| = 1$, $e$ is of finite order, so $e \in H$.

**(iii)** Let $a \in H$. Then, $a \in G$ and is of finite order, say $|a| = n > 0$, so $a^n = e$. Consider $a^{-1} \in G$. Then,

$$
\begin{equation*}(a^{-1})^n = a^{-n} = (a^n)^{-1} = e^{-1} = e.\end{equation*}
$$

Hence, $a^{-1}$ is of finite order, so $a^{-1} \in H$.

$\therefore$ $H \leq G$, as desired. $\blacksquare$$BODY$
  )
on conflict (id) do nothing;
