-- ============================================================================
-- Math 110.1 Exercise 5 — split Q1 (Cyclic Subgroups of Z_12 and D_4)
--
--   Deletes the combined Q1 (cascades bookmarks/progress).
--   Inserts two standalone questions: (a) Z_12 and (b) D_4.
-- ============================================================================

delete from public.questions
where id = '7612d9f0-bb8f-4394-97e0-86c87ae6dec4';

insert into public.questions
  (id, course_id, topic_id, title, question_text, difficulty, year, exam_name, question_number, hint, answer, solution)
values
  (
    -- Q1a — Cyclic subgroups of Z_12
    '7612d9f0-bb8f-4394-97e0-86c87ae6dec5',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Cyclic Subgroups of $\\mathbb{Z}_{12}$',
    $BODY$Consider the group $\mathbb{Z}_{12} = \{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11\}$. Do the following:

- List all the cyclic subgroups of $\mathbb{Z}_{12}$.
- Determine the orders of every element of the group.
- Is $\mathbb{Z}_{12}$ cyclic? If so, identify all the generators.$BODY$,
    'hard',
    2026,
    'Exercise 5',
    1,
    $BODY$List the subgroup generated by each element — they repeat. The number of generators is $\phi(12) = 4$, namely the elements relatively prime to $12$.$BODY$,
    $BODY$The group $\mathbb{Z}_{12}$ is cyclic with generators $1, 5, 7, 11$.$BODY$,
    $BODY$The group $\mathbb{Z}_{12} = \{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11\}$

**Cyclic subgroups:**

- $\langle 0 \rangle = \{0\}$
- $\langle 1 \rangle = \langle 5 \rangle = \langle 7 \rangle = \langle 11 \rangle = \mathbb{Z}_{12}$
- $\langle 2 \rangle = \langle 10 \rangle = \{0, 2, 4, 6, 8, 10\}$
- $\langle 3 \rangle = \langle 9 \rangle = \{0, 3, 6, 9\}$
- $\langle 4 \rangle = \langle 8 \rangle = \{0, 4, 8\}$
- $\langle 6 \rangle = \{0, 6\}$

**Orders of elements:**

$$|0| = 1, \quad |1| = |5| = |7| = |11| = 12, \quad |2| = |10| = 6, \quad |3| = |9| = 4, \quad |4| = |8| = 3, \quad |6| = 2.$$

$\therefore$ $\mathbb{Z}_{12}$ is cyclic with $1, 5, 7$, and $11$ as generators. $\blacksquare$$BODY$
  ),
  (
    -- Q1b — Cyclic subgroups of D_4
    '7612d9f0-bb8f-4394-97e0-86c87ae6dec6',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Cyclic Subgroups of $D_4$',
    $BODY$Consider the dihedral group $D_4 = \{R_{0^{\circ}}, R_{90^{\circ}}, R_{180^{\circ}}, R_{270^{\circ}}, v, h, d_1, d_2\}$. Do the following:

- List all the cyclic subgroups of $D_4$.
- Determine the orders of every element of the group.
- Is $D_4$ cyclic?$BODY$,
    'hard',
    2026,
    'Exercise 5',
    1,
    $BODY$The rotations $R_{0^{\circ}}, R_{90^{\circ}}, R_{180^{\circ}}, R_{270^{\circ}}$ form a cyclic subgroup, and each reflection generates a subgroup of order $2$.$BODY$,
    $BODY$The group $D_4$ is not cyclic — no single element generates all of $D_4$.$BODY$,
    $BODY$The group $D_4 = \{R_{0^{\circ}}, R_{90^{\circ}}, R_{180^{\circ}}, R_{270^{\circ}}, v, h, d_1, d_2\}$

**Cyclic subgroups:**

- $\langle R_{0^{\circ}} \rangle = \{R_{0^{\circ}}\}$
- $\langle R_{90^{\circ}} \rangle = \langle R_{270^{\circ}} \rangle = \{R_{0^{\circ}}, R_{90^{\circ}}, R_{180^{\circ}}, R_{270^{\circ}}\}$
- $\langle R_{180^{\circ}} \rangle = \{R_{0^{\circ}}, R_{180^{\circ}}\}$
- $\langle v \rangle = \{R_{0^{\circ}}, v\}$
- $\langle h \rangle = \{R_{0^{\circ}}, h\}$
- $\langle d_1 \rangle = \{R_{0^{\circ}}, d_1\}$
- $\langle d_2 \rangle = \{R_{0^{\circ}}, d_2\}$

**Orders of elements:**

$$|R_{0^{\circ}}| = 1, \quad |R_{90^{\circ}}| = |R_{270^{\circ}}| = 4, \quad |R_{180^{\circ}}| = |v| = |h| = |d_1| = |d_2| = 2.$$

$\therefore$ $D_4$ is **not** a cyclic group since it has no generator. $\blacksquare$$BODY$
  )
on conflict (id) do nothing;
