-- ============================================================================
-- Math 110.1 Exercise 6 — permutations, disjoint cycles, orders
-- 8 problems with solutions, converted from Typst to Markdown + LaTeX.
-- ============================================================================

insert into public.questions
  (id, course_id, topic_id, title, question_text, difficulty, year, exam_name, question_number, hint, answer, solution)
values
  (
    '1c364386-d7d5-4693-ae98-d3fdc2dc029c',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Products of Cycles as Disjoint Cycles',
    $BODY$Write each of the following permutations as a product of disjoint cycles. Find the order of each permutation.

**(a)** $(1\ 2\ 3\ 5)(4\ 1\ 3)$

**(b)** $(1\ 3\ 2\ 5\ 6)(2\ 3)(4\ 6\ 5\ 1\ 2)$

**(c)** $(1\ 2)(1\ 3)(2\ 3)(1\ 4\ 2)$ $BODY$,
    'medium',
    2026,
    'Exercise 6',
    1,
    $BODY$Compose the cycles from right to left, tracking where each element goes. Then take the least common multiple of the cycle lengths to find the order.$BODY$,
    $BODY$**(a)** $(1\ 5)(2\ 3\ 4)$; order $6$. **(b)** $(1\ 2\ 4)(3\ 5)$; order $6$. **(c)** $(1\ 4\ 2\ 3)$; order $4$.$BODY$,
    $BODY$**(a)**

$$
\begin{equation*}(1\ 2\ 3\ 5)(4\ 1\ 3) = (1\ 5)(2\ 3\ 4).\end{equation*}
$$

$$
\begin{equation*}\left|(1\ 2\ 3\ 5)(4\ 1\ 3)\right| = \mathrm{lcm}(2, 3) = \boxed{6}.\end{equation*}
$$

---

**(b)**

$$
\begin{equation*}(1\ 3\ 2\ 5\ 6)(2\ 3)(4\ 6\ 5\ 1\ 2) = (1\ 2\ 4)(3\ 5).\end{equation*}
$$

$$
\begin{equation*}\left|(1\ 3\ 2\ 5\ 6)(2\ 3)(4\ 6\ 5\ 1\ 2)\right| = \mathrm{lcm}(3, 2) = \boxed{6}.\end{equation*}
$$

---

**(c)**

$$
\begin{equation*}(1\ 2)(1\ 3)(2\ 3)(1\ 4\ 2) = (1\ 4\ 2\ 3).\end{equation*}
$$

$$
\begin{equation*}\left|(1\ 2)(1\ 3)(2\ 3)(1\ 4\ 2)\right| = \boxed{4}.\end{equation*}
$$

$\blacksquare$$BODY$
  ),
  (
    'a2e68b1e-01b7-40ad-934b-bc27bac561c2',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Operations on Permutations in $S_8$',
    $BODY$Let $\alpha = \begin{pmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\ 2 & 3 & 4 & 5 & 1 & 7 & 8 & 6 \end{pmatrix}$ and $\beta = (1\ 5\ 7\ 3\ 2)(3\ 6)(1\ 4\ 6\ 8) \in S_8$.

**(a)** Find $\alpha^{-1}$.

**(b)** Determine $\alpha^4$.

**(c)** Write $\alpha\beta$ using two-row notation.

**(d)** Write $\alpha\beta$ as a product of transpositions.$BODY$,
    'hard',
    2026,
    'Exercise 6',
    2,
    $BODY$Write $\alpha = (1\ 2\ 3\ 4\ 5)(6\ 7\ 8)$ first. Reverse each cycle for $\alpha^{-1}$. For $\alpha^4$, raise each cycle to the $4$th power. For the products, compose right to left.$BODY$,
    $BODY$**(a)** $\alpha^{-1} = (1\ 5\ 4\ 3\ 2)(6\ 8\ 7)$. **(b)** $\alpha^4 = (1\ 5\ 4\ 3\ 2)(6\ 7\ 8)$. **(c)** $\alpha\beta = \begin{pmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\ 5 & 2 & 7 & 3 & 8 & 6 & 4 & 1 \end{pmatrix}$. **(d)** $\alpha\beta = (1\ 5\ 8)(3\ 7\ 4) = (1\ 8)(1\ 5)(3\ 4)(3\ 7)$.$BODY$,
    $BODY$Write $\alpha$ in cycle notation:

$$
\begin{equation*}\alpha = (1\ 2\ 3\ 4\ 5)(6\ 7\ 8).\end{equation*}
$$

**(a)**

$$
\begin{equation*}\alpha^{-1} = (1\ 2\ 3\ 4\ 5)^{-1}(6\ 7\ 8)^{-1} = \boxed{(1\ 5\ 4\ 3\ 2)(6\ 8\ 7)}.\end{equation*}
$$

**(b)**

$$
\begin{equation*}\alpha^4 = (1\ 2\ 3\ 4\ 5)^4 (6\ 7\ 8)^4 = \boxed{(1\ 5\ 4\ 3\ 2)(6\ 7\ 8)}.\end{equation*}
$$

**(c)** Composing $\beta$ then $\alpha$ (right to left),

$$
\begin{equation*}\alpha\beta = (1\ 2\ 3\ 4\ 5)(6\ 7\ 8)(1\ 5\ 7\ 3\ 2)(3\ 6)(1\ 4\ 6\ 8) = \boxed{\begin{pmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\ 5 & 2 & 7 & 3 & 8 & 6 & 4 & 1 \end{pmatrix}}.\end{equation*}
$$

**(d)** Writing $\alpha\beta$ as disjoint cycles first,

$$
\begin{equation*}\alpha\beta = (1\ 5\ 8)(3\ 7\ 4) = \boxed{(1\ 8)(1\ 5)(3\ 4)(3\ 7)}.\end{equation*}
$$

$\blacksquare$$BODY$
  ),
  (
    '4dc0c6ef-aff5-4e6c-9f41-b45890ec1695',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Cyclic and Noncyclic Subgroups of $S_4$',
    $BODY$In $S_4$, find a cyclic subgroup of order $4$ and a noncyclic subgroup of order $4$.$BODY$,
    'medium',
    2026,
    'Exercise 6',
    3,
    $BODY$A cyclic subgroup of order 4 is generated by a 4-cycle. A noncyclic subgroup of order 4 is the Klein-4 subgroup — all four elements are self-inverse, so it has no generator.$BODY$,
    $BODY$Cyclic: $\langle (1\ 2\ 3\ 4) \rangle$. Noncyclic: $\{(1), (1\ 2)(3\ 4), (1\ 3)(2\ 4), (1\ 4)(2\ 3)\}$ (the Klein-4 subgroup).$BODY$,
    $BODY$Consider the cyclic subgroup generated by the 4-cycle $(1\ 2\ 3\ 4) \in S_4$:

$$
\begin{equation*}\left\langle (1\ 2\ 3\ 4) \right\rangle = \{(1), (1\ 2\ 3\ 4), (1\ 3)(2\ 4), (1\ 4\ 3\ 2)\},\end{equation*}
$$

which is cyclic, with $\left|\langle (1\ 2\ 3\ 4) \rangle\right| = 4$.

Consider the set of permutations

$$
\begin{equation*}\{(1), (1\ 2)(3\ 4), (1\ 3)(2\ 4), (1\ 4)(2\ 3)\} \subseteq S_4.\end{equation*}
$$

Since this set is closed under products, contains the identity permutation, and every element is its own inverse, it is a subgroup of $S_4$ of order $4$. Every non-identity element has order $2$, so there is no single generator.

Hence, it is a **noncyclic** subgroup of order $4$. $\blacksquare$$BODY$
  ),
  (
    '629d9669-443d-4533-b021-70339e0534e0',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Elements of Order 5 in $S_7$',
    $BODY$How many elements of order $5$ are in $S_7$?$BODY$,
    'medium',
    2026,
    'Exercise 6',
    4,
    $BODY$Since $5$ is prime, elements of order 5 in $S_7$ are exactly the 5-cycles. Count 5-cycles by fixing the largest element and permuting the rest, then account for the 5 rotations of each cycle.$BODY$,
    $BODY$There are $\boxed{504}$ elements of order $5$ in $S_7$.$BODY$,
    $BODY$Since $5$ is prime, the elements of order $5$ in $S_7$ are exactly the $5$-cycles.

- For cycles with $7$ as the highest element, $(7\ \_\ \_\ \_\ \_)$: $6 \cdot 5 \cdot 4 \cdot 3 = 360$ elements.
- For cycles with $6$ as the highest element, $(6\ \_\ \_\ \_\ \_)$: $5 \cdot 4 \cdot 3 \cdot 2 = 120$ elements.
- For cycles with $5$ as the highest element, $(5\ \_\ \_\ \_\ \_)$: $4 \cdot 3 \cdot 2 \cdot 1 = 24$ elements.

Hence, there are $360 + 120 + 24 = \boxed{504}$ elements of order $5$ in $S_7$. $\blacksquare$$BODY$
  ),
  (
    'b361931d-9d7e-45da-90ea-e60988c6a1ad',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Elements of Order 4 and Order 2 in $S_6$',
    $BODY$How many elements of order $4$ does $S_6$ have? How many elements of order $2$ does $S_6$ have?$BODY$,
    'hard',
    2026,
    'Exercise 6',
    5,
    $BODY$For order 4, the cycle structure must be a 4-cycle (with lcm 4) or a 4-cycle times a 2-cycle. For order 2, use that 2 is prime, so the elements are exactly the transpositions.$BODY$,
    $BODY$Order $4$: $\boxed{180}$ elements. Order $2$: $\boxed{15}$ elements.$BODY$,
    $BODY$**Order 4**

Note that $4 = \mathrm{lcm}(4, 2) = \mathrm{lcm}(4, 1)$. Hence, we want permutations that are either a product of a $4$-cycle and a $2$-cycle, or a $4$-cycle alone.

- Product of a $4$-cycle and a $2$-cycle:
  $$(6 \cdot 5 \cdot 4 \cdot 3) \cdot \frac{1}{4} \cdot (2 \cdot 1) \cdot \frac{1}{2} = 90 \text{ elements}.$$
- $4$-cycles:
  $$(6 \cdot 5 \cdot 4 \cdot 3) \cdot \frac{1}{4} = 90 \text{ elements}.$$

Hence, there are $90 + 90 = \boxed{180}$ elements of order $4$ in $S_6$. $\blacksquare$

---

**Order 2**

Note that $2$ is prime. Hence, the elements of order $2$ are exactly the $2$-cycles.

- $2$-cycles:
  $$(6 \cdot 5) \cdot \frac{1}{2} = 15 \text{ elements}.$$

Hence, there are $\boxed{15}$ elements of order $2$ in $S_6$. $\blacksquare$$BODY$
  ),
  (
    '0526245a-79c1-4b81-bbc2-d5db6a53a97b',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Smallest $n$ with $\\beta^n = \\beta^{-5}$',
    $BODY$Let $\beta = (1\ 3\ 5\ 7\ 9\ 8\ 6)(2\ 4\ 10) \in S_{10}$. What is the smallest positive integer $n$ for which $\beta^n = \beta^{-5}$?$BODY$,
    'hard',
    2026,
    'Exercise 6',
    6,
    $BODY$Find $|\beta| = \mathrm{lcm}(7, 3)$. Then $\beta^n = \beta^{-5}$ is equivalent to $\beta^{n + 5} = e$, so $n + 5$ must be a multiple of $|\beta|$; pick the smallest positive such $n$.$BODY$,
    $BODY$The smallest positive integer is $\boxed{n = 16}$.$BODY$,
    $BODY$Note that $|\beta| = \mathrm{lcm}(7, 3) = 21$. Therefore, $\beta^{21} = (1)$, and

$$
\begin{equation*}\beta^{21} = (1) \implies \beta^{16} = \beta^{-5} \implies \boxed{n = 16}.\end{equation*}
$$

$\blacksquare$$BODY$
  ),
  (
    '1ab88405-a81b-4b0a-999d-74f476eef976',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Find $\\sigma \\in S_7$ Given $\\sigma^4$',
    $BODY$Let $\sigma \in S_7$ and suppose $\sigma^4 = (2\ 1\ 4\ 3\ 5\ 6\ 7)$. Find $\sigma$.$BODY$,
    'hard',
    2026,
    'Exercise 6',
    7,
    $BODY$Note that $(\sigma^4)^2 = \sigma^8$. Since $\sigma^7 = e$ (as $\sigma$ must be a 7-cycle), we have $\sigma^8 = \sigma$. Compute $(\sigma^4)^2$.$BODY$,
    $BODY$Squaring the given 7-cycle gives $\boxed{\sigma = (2\ 4\ 5\ 7\ 1\ 3\ 6)}$.$BODY$,
    $BODY$Since $\sigma^4$ is a 7-cycle, $\sigma$ is a 7-cycle, so $\sigma^7 = (1)$ and $\sigma^8 = \sigma$. Then,

$$
\begin{equation*}(\sigma^4)^2 = \sigma^8 = \sigma.\end{equation*}
$$

Squaring $(2\ 1\ 4\ 3\ 5\ 6\ 7)$,

$$
\begin{equation*}\sigma = (2\ 1\ 4\ 3\ 5\ 6\ 7)^2 = \boxed{(2\ 4\ 5\ 7\ 1\ 3\ 6)}.\end{equation*}
$$

$\blacksquare$$BODY$
  ),
  (
    'a9b4b64d-880e-430f-9de7-e61c79059176',
    'cd574181-02fb-4093-9e23-f268fea6baff',
    'd210d4b4-a572-5804-bdfa-71052bd7dc1b',
    'Find $\\beta, \\gamma \\in S_4$ From Their Products',
    $BODY$Suppose that $\beta$ and $\gamma$ are in $S_4$ with $\beta\gamma = (1\ 4\ 3\ 2)$, $\gamma\beta = (1\ 2\ 4\ 3)$ and $\beta(1) = 4$. Determine $\beta$ and $\gamma$.$BODY$,
    'hard',
    2026,
    'Exercise 6',
    8,
    $BODY$Work element by element. Use $\beta(1) = 4$ together with the two product cycles to determine how each permutation acts on $1, 2, 3, 4$ in sequence.$BODY$,
    $BODY$$\boxed{\beta = (1\ 4\ 2\ 3)}$ and $\boxed{\gamma = (2\ 3\ 4)}$.$BODY$,
    $BODY$Using the given cycles for $\beta\gamma$ and $\gamma\beta$, we get:

$$
\begin{aligned}
\beta(1) &= 4 \implies \gamma(4) = 2 \implies \beta(2) = 3 \implies \gamma(3) = 4, \\
\beta(4) &= 2 \implies \gamma(2) = 3 \implies \beta(3) = 1 \implies \gamma(1) = 1.
\end{aligned}
$$

Hence, $\beta = \boxed{(1\ 4\ 2\ 3)}$ and $\gamma = \boxed{(2\ 3\ 4)}$. $\blacksquare$$BODY$
  )
on conflict (id) do nothing;
