-- ============================================================================
-- Seed: MATH 110.3 Abstract Algebra III — Unit I notes
-- ============================================================================

-- Ensure the course exists
insert into public.courses (id, code, name, description)
values (
  '9f9a5e39-6e48-4ae6-a455-37c3a5cfb4ab',
  'MATH 110.3',
  'Abstract Algebra III',
  'Factorization, ideals, UFDs, and Euclidean domains.'
)
on conflict (code) do update set id = excluded.id;

insert into public.course_notes
  (id, course_id, title, content, sort_order)
values
  (
    'e5f6a7b8-c9d0-4e1f-a2b3-c4d5e6f7a8b9',
    '9f9a5e39-6e48-4ae6-a455-37c3a5cfb4ab',
    'Unit I: Factorization, Ideals, UFDs, and Euclidean Domains',
$BODY$# 1. Factorization of Polynomials over a Field

---

## Division Algorithm for $F[x]$

### Recall: Division Algorithm for $\mathbb{Z}$

Let $m, n \in \mathbb{Z}$ with $n > 0$. Then there exist unique integers $q$ and $r$ with the property

$$m = nq + r,$$

where $0 \leq r < n$.

### Theorem 1.3: Division Algorithm for $F[x]$

Let $F$ be a field, and $f(x), g(x) \in F[x]$ with $g(x) \neq 0$.

Then there exist unique polynomials $q(x), r(x) \in F[x]$ with the property that

$$f(x) = q(x)g(x) + r(x)$$

where $r(x) = 0$ or $\deg r(x) < \deg g(x)$.

### Remark

We call the unique polynomials $q(x)$ and $r(x)$ in Theorem 1.3 the **quotient** and **remainder**, respectively, upon dividing $f(x)$ by $g(x)$.

---

## Polynomial Factors

### Definition

Let $F$ be a field and $f(x) = a_0 + a_1 x + \cdots + a_n x^n \in F[x]$.

1. Then $g(x) \in F[x]$ is said to **divide** $f(x)$ or is a **factor** of $f(x)$ if there exists $q(x) \in F[x]$ such that $f(x) = q(x)g(x)$.
2. If $\alpha \in F$, then $f(\alpha) := a_0 + a_1 \alpha + \cdots + a_n \alpha^n$.
3. Here, we need the ring $R$ to be commutative so that if $f(x), g(x) \in F[x]$ and $h(x) := f(x)g(x)$, then $h(\alpha) = f(\alpha)g(\alpha)$.

---

## Consequences of the Division Algorithm for $F[x]$

### Corollary 1.4: Remainder Theorem

Let $F$ be a field, and $a \in F$. Then the remainder when $f(x) \in F[x]$ is divided by $x - a$ is $f(a)$.

### Corollary 1.5: Factor Theorem

Let $F$ be a field, $a \in F$, and $f(x) \in F[x]$. Then $x - a$ is a factor of $f(x)$ if and only if $f(a) = 0$.

### Corollary 1.6

A polynomial $f(x) \in F[x]$ of positive degree $n$ has at most $n$ distinct zeros in the field $F$.

### Remark

1. Lagrange first proved Corollary 1.6 for $F = \mathbb{Z}_p$.
2. Corollary 1.6 is not true for arbitrary polynomial rings.

---

# 2. Review of Ideals, Factor Rings, and Homomorphisms

---

## Ideals

### Recall

1. An **ideal** $I$ of a ring $R$ is a subring of $R$ such that for every $r \in R$ and for every $a \in I$, $ra \in I$ and $ar \in I$.
2. **Ideal Test:** Let $R$ be a ring. Then $\emptyset \neq I \subseteq R$ is an ideal of $R$ if and only if:
   - (a) for all $a, b \in I$, $a - b \in I$, and
   - (b) for all $r \in R$ and for all $a \in I$, $ra \in I$ and $ar \in I$.
3. If $R$ is a ring with unity, and $I$ is an ideal of $R$ containing a unit, then $I = R$.
4. The ideals of a field $F$ are $\{0\}$ and $F$.

---

## Principal Ideals

### Definition

Let $R$ be a commutative ring with unity.

1. If $a \in R$ then the ideal $\langle a \rangle := \{ra \mid r \in R\}$ is called the **principal ideal** generated by $a$.
2. An ideal $I$ of $R$ is said to be a **principal ideal** if $I = \langle a \rangle$ for some $a \in R$.

---

## Ideals of $F[x]$

### Theorem 1.13

Let $F$ be a field. Then every ideal of $F[x]$ is a principal ideal.

### Remark

Let $F$ be a field.

1. Suppose $\{0\} \neq I$ is an ideal of $F[x]$ and $g(x) \in F[x]$. Then $I = \langle g(x) \rangle$ if and only if $g(x)$ is a non-zero polynomial of minimum degree in $I$.
2. If $f(x), g(x) \in F[x]$, then $f(x)$ divides $g(x)$ if and only if $\langle f(x) \rangle \supseteq \langle g(x) \rangle$.

---

## Factor Rings

### Recall

Let $I$ be an ideal of a ring $R$.

1. The **factor ring** (or quotient ring) of $R$ modulo $I$ is the set $R/I = \{a + I \mid a \in R\}$ together with the binary operations
$$(a + I) + (b + I) = (a + b) + I,$$
$$(a + I)(b + I) = ab + I.$$

   Its additive identity is $0 + I = I$, and if $a + I \in R/I$ then $-(a + I) = -a + I$.

2. If $R$ is commutative, then $R/I$ is commutative.
3. If $R$ has unity $1$, then $R/I$ has unity $1 + I$. In addition, if $a$ is a unit of $R$, then $a + I$ is a unit of $R/I$ with
$$(a + I)^{-1} = a^{-1} + I.$$

---

## Maximal and Prime Ideals

### Recall

Let $R$ be a ring.

1. An ideal $M \neq R$ is a **maximal ideal** of $R$ if whenever $I$ is an ideal of $R$ such that $M \subseteq I \subseteq R$, then $I = M$ or $I = R$.
2. If $R$ is commutative, then an ideal $P \neq R$ is a **prime ideal** of $R$ if whenever $a, b \in R$ such that $ab \in P$, then $a \in P$ or $b \in P$.

### Recall

Let $R$ be a commutative ring with unity $1 \neq 0$, and $I$ an ideal of $R$.

1. Then $R/I$ is a **field** if and only if $I$ is a **maximal ideal** of $R$.
2. Then $R/I$ is an **integral domain** if and only if $I$ is a **prime ideal** of $R$.
3. If $I$ is a maximal ideal of $R$, then $I$ is a prime ideal of $R$.

---

## Maximal Ideals of $F[x]$

### Theorem 1.14

Let $F$ be a field and $p(x) \in F[x]$. Then $\langle p(x) \rangle$ is a maximal ideal of $F[x]$ if and only if $p(x)$ is irreducible over $F$.

### Remark

If $F$ is a field, and $p(x)$ is an irreducible polynomial in $F[x]$, then $F[x] / \langle p(x) \rangle$ is a field.

---

## Primes in $F[x]$

### Corollary 1.5

Let $F$ be a field and $p(x), r(x), s(x) \in F[x]$.

If $p(x)$ is irreducible over $F$ and $p(x)$ divides $r(x)s(x)$, then $p(x)$ divides $r(x)$ or $p(x)$ divides $s(x)$.

### Remark

In general, suppose $F$ is a field and $p(x), r_1(x), r_2(x), \ldots, r_n(x) \in F[x]$.

If $p(x)$ is irreducible over $F$ and $p(x)$ divides $r_1(x) r_2(x) \cdots r_n(x)$, then $p(x)$ divides $r_i(x)$ for at least one $i$, $1 \leq i \leq n$.

---

## Unique Factorization in $F[x]$

### Theorem 1.6

Let $F$ be a field. Then every non-constant polynomial $f(x) \in F[x]$ can be factored in $F[x]$ into a product of irreducible polynomials over $F$, the irreducible polynomials being unique except for order and for unit factors in $F$.

---

## Homomorphisms

### Recall

Let $R$ and $R'$ be rings.

1. A **ring homomorphism** from $R$ to $R'$ is a mapping $\varphi : R \to R'$ such that for any $a, b \in R$,
$$\varphi(a + b) = \varphi(a) + \varphi(b),$$
$$\varphi(ab) = \varphi(a)\varphi(b).$$

2. An **isomorphism** from $R$ to $R'$ is a bijective homomorphism from $R$ to $R'$. The rings $R$ and $R'$ are **isomorphic**, written $R \cong R'$, if there is an isomorphism from $R$ to $R'$.

### Evaluation Homomorphism

### Remark

Let $F$ be a subfield of a field $E$, and $\alpha \in E$. Then $\varphi_\alpha : F[x] \to E$ given by
$$\varphi_\alpha(a_0 + a_1 x + \cdots + a_n x^n) = a_0 + a_1 \alpha + \cdots + a_n \alpha^n$$
is a homomorphism of $F[x]$ into $E$ called the **evaluation homomorphism** at $\alpha$.

The homomorphism $\varphi_\alpha$ satisfies the following properties:

1. $\varphi_\alpha(x) = \alpha$
2. If $a \in F$ then $\varphi_\alpha(a) = a$.

### Recall

Let $\varphi : R \to R'$ be a ring homomorphism.

1. The **kernel** of $\varphi$ is
$$\ker \varphi = \{a \in R \mid \varphi(a) = 0'\},$$
where $0'$ is the additive identity of $R'$.
2. The kernel of $\varphi$ is an ideal of $R$.
3. **First Isomorphism Theorem for Rings:** The map $\mu : R / \ker \varphi \to \varphi(R)$, given by $a + \ker \varphi \mapsto \varphi(a)$ is a ring isomorphism and so
$$R / (\ker \varphi) \cong \varphi(R).$$

---

# 3. Unique Factorization Domains

---

## Factorization in Commutative Rings with Unity

### Recall

The rings $\mathbb{Z}$ and $F[x]$ (where $F$ is a field) are integral domains having several common properties.

**Extra Reading:** Effinger, Hicks, and Mullen, *Integers and Polynomials: Comparing the Close Cousins $\mathbb{Z}$ and $\mathbb{F}_q[x]$*

### Definition

Let $R$ be a commutative ring with unity, and $a, b \in R$. Then $a$ is said to **divide** $b$ (or $a$ is a factor of $b$, or $a$ is a divisor of $b$), denoted $a \mid b$, if there exists $c \in R$ such that $b = ac$.

### Remark

We write $a \nmid b$ whenever $a$ does not divide $b$.

### Remark

Let $a, b, c$ be elements of a commutative ring $R$ with unity $1$.

1. Then $a \mid a$, $1 \mid a$, and $a \mid 0$.
2. Then $a$ is a unit if and only if $a \mid 1$.
3. If $a \mid b$ and $b \mid c$, then $a \mid c$.
4. Then $a \mid b$ if and only if $\langle b \rangle \subseteq \langle a \rangle$.

---

## Associates

### Definition

Let $R$ be a commutative ring with unity, and $a, b \in R$. Then $b$ is said to be an **associate** of $a$ if $b = au$ for some unit $u \in R$.

### Remark

1. Let $R$ be a commutative ring with unity. Then the relation $a \sim b$ on $R$ where $b$ is an associate of $a$ defines an equivalence relation on $R$.
2. Let $D$ be an integral domain, and $a, b \in D$. Then the following are equivalent:
   - (i) $a$ and $b$ are associates
   - (ii) $a \mid b$ and $b \mid a$
   - (iii) $\langle a \rangle = \langle b \rangle$

---

## Irreducibles and Primes

### Definition

Let $D$ be an integral domain, and $0 \neq p \in D$ that is not a unit.

1. Then $p$ is an **irreducible** of $D$ if, whenever $a, b \in D$ such that $p = ab$, then either $a$ is a unit or $b$ is a unit.
2. Then $p$ is a **prime** of $D$ if, whenever $a, b \in D$ such that $p \mid ab$, then $p \mid a$ or $p \mid b$.

### Remark

Let $D$ be an integral domain, and $p \in D$.

1. If $p$ is an irreducible, then any associate of $p$ is also irreducible.
2. Then $p$ is a prime if and only if $\langle p \rangle$ is a non-zero prime ideal of $D$.

### Theorem 1.17

Let $D$ be an integral domain. Then every prime of $D$ is an irreducible of $D$.

---

## Principal Ideal Domains

### Definition

An integral domain $D$ is a **principal ideal domain** (PID) if every ideal of $D$ is a principal ideal.

### Theorem 1.18

Let $D$ be a PID. Then $p$ is an irreducible of $D$ if and only if $p$ is a prime of $D$.

---

## Unique Factorization Domains

### Definition

An integral domain $D$ is a **unique factorization domain** (UFD) if the following hold:

1. Every non-zero non-unit element of $D$ can be written as a product of a finite number of irreducibles of $D$.
2. The factorization of a non-zero non-unit element of $D$ into irreducibles of $D$ is unique up to associates and the order in which the factors appear.

### Remark

Condition 2 means that if $p_1 p_2 \cdots p_r$ and $q_1 q_2 \cdots q_s$ are two factorizations of some element of $D$ into irreducibles of $D$, then $r = s$ and for all $i \in \{1, 2, \ldots, s\}$, $q_i$ is an associate of some $p_j$, where $1 \leq j \leq r$.

**Extra Reading:** *New Number Systems Seek Their Lost Primes* by Kevin Hartnett

### Remark

If $D$ is a UFD, then $p$ is an irreducible of $D$ if and only if $p$ is a prime of $D$.

### Lemma 1.19

Let $R$ be a commutative ring. If $I_1 \subseteq I_2 \subseteq \cdots$ is an ascending chain of ideals $I_i$ in $R$, then $I = \bigcup_i I_i$ is an ideal of $R$.

---

## Ascending Chain of Ideals

### Lemma 1.20: Ascending Chain Condition for a PID

Let $D$ be a PID. If $I_1 \subseteq I_2 \subseteq \cdots$ is an ascending chain of ideals $I_i$ in $D$, then there exists a positive integer $r$ such that $I_s = I_r$ for $s \geq r$.

### Remark

1. Lemma 1.20 is equivalent to: In a PID, every strictly ascending chain of ideals $I_1 \subset I_2 \subset \cdots$ is of finite length.
2. We say that in a PID, the **ascending chain condition** (ACC) holds.

---

## PID $\Rightarrow$ UFD

### Theorem 1.21

Every PID is a UFD.

**Question:** UFD $\Rightarrow^{?}$ PID

**Answer:** No!

---

## Greatest Common Divisor

Let $D$ be a UFD, and $a_1, a_2, \ldots, a_n \in D$. Then $d \in D$ is called a **greatest common divisor** ($\gcd$) of $a_1, a_2, \ldots, a_n$ if

1. $d \mid a_i$ for $i \in \{1, 2, \ldots, n\}$, and
2. whenever $c \in D$ such that $c \mid a_i$ for $i \in \{1, 2, \ldots, n\}$, then $c \mid d$.

### Remark

Let $D$ be a UFD.

1. The $\gcd$ of a set of elements of $D$ is not unique. In fact, if $d$ and $d'$ are $\gcd$s of the same elements of $D$, then $d$ and $d'$ are associates.
2. A $\gcd$ of a set of elements of $D$ always exists.

---

## Content of a Polynomial

### Definition

Let $D$ be a UFD, and $f(x) = a_0 + a_1 x + \cdots + a_n x^n$ be a non-zero polynomial in $D[x]$.

1. The **content** of $f(x)$ is a $\gcd$ of $a_0, a_1, \ldots, a_n$.
2. Then $f(x)$ is said to be **primitive** if the content of $f(x)$ is a unit.

### Remark

Let $D$ be a UFD and $0 \neq f(x) \in D[x]$.

1. The content of $f(x)$ is unique up to associates.
2. If the content of $f(x)$ is $1$, then $f(x)$ is primitive.
3. Then $f(x)$ can be written as $f(x) = c \cdot g(x)$, where $c$ is the content of $f(x)$, and $g(x) \in D[x]$ with $g(x)$ primitive.
4. If $f(x) = d \cdot g(x)$, where $g(x)$ is a primitive polynomial in $D[x]$, then the content of $f(x)$ and $d$ are associates.
5. If $\deg f(x) > 0$ and $f(x)$ is an irreducible of $D[x]$, then $f(x)$ is primitive.

---

## Gauss' Lemma

### Lemma 1.22: Gauss' Lemma

If $D$ is a UFD, then the product of two primitive polynomials in $D[x]$ is again primitive.

### Remark

Let $D$ be a UFD. Then a finite product of primitive polynomials in $D[x]$ is still primitive.

---

## Irreducibles of $D[x]$

### Recall

The field of quotients $F$ of an integral domain $D$ is
$$F = \{a/b \mid a, b \in D, b \neq 0\},$$
and
$$D \cong \{a/1 \mid a \in D\} \subseteq F.$$

### Lemma 1.23

Let $D$ be a UFD, and $F$ be the field of quotients of $D$. If $f(x)$ is a non-constant polynomial in $D[x]$, then $f(x)$ is irreducible over $F$ whenever $f(x)$ is an irreducible of $D[x]$.

### Remark

1. Theorem 1.8 now follows from Lemma 1.23 and its proof.
2. Let $D$ be a UFD, and $F$ its field of quotients. If a non-constant $f(x) \in D[x]$ is primitive and is irreducible over $F$, then $f(x)$ is an irreducible of $D[x]$.
3. If $D$ is a UFD, then the irreducibles of $D[x]$ are the irreducibles of $D$, together with the non-constant primitive polynomials that are irreducible over $F$, where $F$ is the field of quotients of $D$.

---

## $D$ UFD $\Rightarrow$ $D[x]$ UFD

### Theorem 1.24

If $D$ is a UFD, then $D[x]$ is a UFD.

---

# 4. Euclidean Domains

---

### Definition

An integral domain $D$ is said to be a **Euclidean domain** (ED) if there is a function
$$v : D \setminus \{0\} \to \mathbb{N}_0 := \mathbb{N} \cup \{0\}$$
(called **Euclidean norm** / Euclidean valuation / measure on $D$) that satisfies the following:

1. For all $a, b \in D \setminus \{0\}$, $v(ab) \geq v(a)$.
2. For all $a, b \in D$, with $b \neq 0$, there exist $q, r \in D$ such that
$$a = bq + r,$$
where either $r = 0$ or $v(r) < v(b)$.

### Remark

The elements $q$ and $r$ in condition 2 are not unique.

---

## ED $\Rightarrow$ PID

### Recall

$\mathbb{Z}$ and $F[x]$ ($F$ a field) are PIDs.

### Theorem 1.25

Every ED is a PID.

### Remark

1. Every ED is a UFD.
2. Not every PID is an ED. e.g.: $\mathbb{Z}[\sqrt{-19}] = \{a + b(1 + \sqrt{-19})/2 \mid a, b \in \mathbb{Z}\}$ is a PID but not an ED (T. Motzkin, 1949).

**Extra Reading:** Campoli, *A principal ideal domain that is not a Euclidean domain*

---

## Integral Domains

The hierarchy of integral domains:

$$\text{ED} \Rightarrow \text{PID} \Rightarrow \text{UFD}$$

---

## $v(1)$

### Theorem 1.26

Let $D$ be an ED with Euclidean norm $v$.

1. Then $v(1)$ is minimal among all $v(a)$, where $a \in D \setminus \{0\}$.
2. Then $u \in D \setminus \{0\}$ is a unit if and only if $v(u) = v(1)$.

---

## Multiplicative Norms

### Definition

Let $D$ be an integral domain. A **multiplicative norm** on $D$ is a function $N : D \to \mathbb{Z}$ that satisfies the following:

1. $N(\alpha) = 0$ if and only if $\alpha = 0$
2. For all $\alpha, \beta \in D$, $N(\alpha\beta) = N(\alpha)N(\beta)$.

### Theorem 1.27

Let $D$ be an integral domain, and $N$ a multiplicative norm on $D$.

1. Then $N(1) = 1$.
2. If $u \in D$ is a unit, then $|N(u)| = 1$.
3. Suppose every $\alpha \in D$ such that $|N(\alpha)| = 1$ is a unit. Then $\pi$ is an irreducible of $D$ whenever $|N(\pi)| = p$, where $p$ is a prime in $\mathbb{Z}$.

### Remark: Fermat

Let $p$ be an odd prime in $\mathbb{Z}$. Then $p = a^2 + b^2$ for some $a, b \in \mathbb{Z}$ if and only if $p \equiv 1 \pmod{4}$.$BODY$,
    1
  )
on conflict (id) do nothing;
